name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@7.0.0
      with:
        docs-folder: docs/
        pre-build-command: >
          apt-get update -y
          && apt-get install -y wget
          && wget -nc https://github.com/ipython/xkcd-font/blob/master/xkcd-script/font/xkcd-script.ttf?raw=true -O /usr/local/share/fonts/xkcd-Script.ttf
          && wget -nc https://github.com/ipython/xkcd-font/blob/master/xkcd/build/xkcd.otf?raw=true -O /usr/local/share/fonts/xkcd.otf
          && wget -O Comic_Neue.zip https://fonts.google.com/download?family=Comic%20Neue
          && unzip -d comic_neue/ Comic_Neue.zip
          && comic_neue /usr/share/fonts/
          && fc-cache -f -v
        build-command: "sphinx-build -b dirhtml source build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
